### ISSUE TITLE
unclose iterator

### ISSUE THREAD

**Issue by baabeetaa** [baabeetaa/osmosis#1]
I updated the tm-db to find unclosed iterator. Basically, what it does:
- assign an id for each new  iterator, and log its caller stack (`https://github.com/baabeetaa/tm-db/blob/v0.6.7-fix-itr/pebble.go#L338`)
- log closed iterator with its id (`https://github.com/baabeetaa/tm-db/blob/v0.6.7-fix-itr/pebble.go#L443`)

The log file: (warning the uncompressed file is ~900MB)
[log.txt.tar.gz](https://github.com/baabeetaa/osmosis/files/9389277/log.txt.tar.gz)

To find all closed iterator in the log: 
```cat log.txt |grep "close iterator id=" > close.txt```

then you 'll got a file:
```
close iterator id=1
close iterator id=2
close iterator id=3
close iterator id=4
close iterator id=5
...
```

The unclosed iterators is the one missing in the `close.txt` file

For example: missing iterator id 66
```
close iterator id=55
close iterator id=56
close iterator id=57
close iterator id=58
close iterator id=59
close iterator id=60
close iterator id=61
close iterator id=62
close iterator id=63
close iterator id=64
close iterator id=65
close iterator id=67
close iterator id=68
close iterator id=70
close iterator id=71
close iterator id=72
close iterator id=73
close iterator id=74
close iterator id=75
```

Next, find the stack when opening iterator with id 66 in the `log.txt`:

```
-------------------------------------------------------------
open iterator id=66, Iterator counter: 1 
#66: goroutine 1 [running]:
github.com/tendermint/tm-db.newPebbleDBIterator(0xc001ac6500, {0xc0028124b0, 0x22, 0x30}, {0xc0028124e0, 0x22, 0x30}, 0x1)
	/root/tm-db/pebble.go:341 +0x1fe
github.com/tendermint/tm-db.(*PebbleDB).ReverseIterator(0xb?, {0xc0028124b0, 0x22, 0x30}, {0xc0028124e0, 0x22, 0x30})
	/root/tm-db/pebble.go:224 +0x18f
github.com/tendermint/tm-db.(*PrefixDB).ReverseIterator(0xc0043c4c60, {0xc002783170, 0x17, 0x17}, {0xc002783188, 0x17, 0x17})
	/root/tm-db/prefixdb.go:149 +0x383
github.com/cosmos/iavl.(*nodeDB).getFastIterator(0xc0043e8120, {0xc002783140?, 0xc000580c00?, 0xc002707ab0?}, {0xc002783158, 0x16, 0x16}, 0x0)
	/root/iavl/nodedb.go:803 +0x196
github.com/cosmos/iavl.(*FastIterator).Next(0xc002707ab0)
	/root/iavl/fast_iterator.go:107 +0x6f
github.com/cosmos/iavl.NewFastIterator({0xc002783140, 0x16, 0x16}, {0xc002783158, 0x16, 0x16}, 0x0, 0xc0043e8120)
	/root/iavl/fast_iterator.go:43 +0xfc
github.com/cosmos/iavl.NewUnsavedFastIterator({0xc002783140, 0x16, 0x16}, {0xc002783158, 0x16, 0x16}, 0x0, 0xc0043e8120, 0xc0043c5170, 0xc0043c5200)
	/root/iavl/unsaved_fast_iterator.go:62 +0xca
github.com/cosmos/iavl.(*MutableTree).Iterator(0xc00033fc20, {0xc002783140, 0x16, 0x16}, {0xc002783158, 0x16, 0x16}, 0x68?)
	/root/iavl/mutable_tree.go:188 +0xa5
github.com/cosmos/cosmos-sdk/store/iavl.(*Store).ReverseIterator(0xc0027fb080?, {0xc002783140?, 0x180?, 0x3870780?}, {0xc002783158?, 0x41a88d?, 0x7fc168306c30?})
	/root/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220728141005-f09814c9e23f/store/iavl/store.go:228 +0x2e
github.com/cosmos/cosmos-sdk/store/cachekv.(*Store).iterator(0xc002863dc0, {0xc002783140, 0x16, 0x16}, {0xc002783158, 0x16, 0x16}, 0x0)
	/root/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220728141005-f09814c9e23f/store/cachekv/store.go:191 +0x137
github.com/cosmos/cosmos-sdk/store/cachekv.(*Store).ReverseIterator(0x7fc1915d9108?, {0xc002783140?, 0xc000580c00?, 0xc0027fb0b0?}, {0xc002783158?, 0xc00249d115?, 0xc00249d1c0?})
	/root/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220728141005-f09814c9e23f/store/cachekv/store.go:179 +0x26
github.com/cosmos/cosmos-sdk/store/cachekv.(*Store).iterator(0xc00273f4c0, {0xc002783140, 0x16, 0x16}, {0xc002783158, 0x16, 0x16}, 0x0)
	/root/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220728141005-f09814c9e23f/store/cachekv/store.go:191 +0x137
github.com/cosmos/cosmos-sdk/store/cachekv.(*Store).ReverseIterator(0x0?, {0xc002783140?, 0x3870780?, 0x0?}, {0xc002783158?, 0x5?, 0x41b0ff?})
	/root/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220728141005-f09814c9e23f/store/cachekv/store.go:179 +0x26
github.com/cosmos/cosmos-sdk/store/gaskv.(*Store).iterator(0xc0027db1a0, {0xc002783140?, 0x0?, 0xc004fe4600?}, {0xc002783158?, 0xf?, 0x1?}, 0x58?)
	/root/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220728141005-f09814c9e23f/store/gaskv/store.go:109 +0x69
github.com/cosmos/cosmos-sdk/store/gaskv.(*Store).ReverseIterator(0x3?, {0xc002783140?, 0x41b0ff?, 0xc001e8b580?}, {0xc002783158?, 0x204ac00?, 0xc0001b00f0?})
	/root/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220728141005-f09814c9e23f/store/gaskv/store.go:86 +0x26
github.com/cosmos/cosmos-sdk/store/prefix.Store.ReverseIterator({{0x278a7c8, 0xc0027db1a0}, {0xc001e8b580, 0xf, 0xf}}, {0xc001e8b800, 0x7, 0x7}, {0xc001e8b7f8, 0x7, ...})
	/root/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220728141005-f09814c9e23f/store/prefix/store.go:118 +0x239
github.com/osmosis-labs/osmosis/v10/store.Tree.ptrReverseIterator({{0x278b7a0?, 0xc0027fa810?}, 0x0?}, 0x2, {0x0, 0x0, 0xf?}, {0xc00233dd5b, 0x0, 0x0})
	/root/osmosis/store/tree.go:191 +0x2af
github.com/osmosis-labs/osmosis/v10/store.(*ptr).leftSibling(0xc002810100?)
	/root/osmosis/store/node.go:57 +0x5f
github.com/osmosis-labs/osmosis/v10/store.(*ptr).parent(0xc002810000)
	/root/osmosis/store/node.go:88 +0xf7
github.com/osmosis-labs/osmosis/v10/store.(*ptr).updateAccumulation(0xc002810000, 0xc0027ee7a0)
	/root/osmosis/store/node.go:118 +0x15f
github.com/osmosis-labs/osmosis/v10/store.(*ptr).push(0xc002810000, 0xc0027ee7a0)
	/root/osmosis/store/node.go:132 +0x81f
github.com/osmosis-labs/osmosis/v10/store.Tree.Set({{0x278b7a0?, 0xc0027fa810?}, 0x0?}, {0xc001e8b5f0, 0x8, 0x8}, {0xc004fe4c70?})
	/root/osmosis/store/tree.go:45 +0x129
github.com/osmosis-labs/osmosis/v10/store.Tree.Increase({{0x278b7a0?, 0xc0027fa810?}, 0x48?}, {0xc001e8b5f0, 0x8, 0x8}, {0x277ae90?})
	/root/osmosis/store/tree.go:60 +0x8b
github.com/osmosis-labs/osmosis/v10/x/lockup/keeper.Keeper.lock({{0x2791f98, 0xc001218c40}, {0x2763d48, 0xc0012a1b00}, {0x27842c0, 0xc000fa9110}, {0x277ae90, 0xc000e982d0}, {0x27850c0, 0xc0016da000}, ...}, ...)
	/root/osmosis/x/lockup/keeper/lock.go:142 +0x395
github.com/osmosis-labs/osmosis/v10/x/lockup/keeper.Keeper.AddTokensToLockByID({{0x2791f98, 0xc001218c40}, {0x2763d48, 0xc0012a1b00}, {0x27842c0, 0xc000fa9110}, {0x277ae90, 0xc000e982d0}, {0x27850c0, 0xc0016da000}, ...}, ...)
	/root/osmosis/x/lockup/keeper/lock.go:80 +0x2fb
github.com/osmosis-labs/osmosis/v10/x/lockup/keeper.Keeper.AddToExistingLock({{0x2791f98, 0xc001218c40}, {0x2763d48, 0xc0012a1b00}, {0x27842c0, 0xc000fa9110}, {0x277ae90, 0xc000e982d0}, {0x27850c0, 0xc0016da000}, ...}, ...)
	/root/osmosis/x/lockup/keeper/lock.go:57 +0x191
github.com/osmosis-labs/osmosis/v10/x/lockup/keeper.msgServer.LockTokens({0x419105?}, {0x277be78?, 0xc0027fa000?}, 0xc002787200)
	/root/osmosis/x/lockup/keeper/msg_server.go:42 +0x1e5
github.com/osmosis-labs/osmosis/v10/x/lockup/types._Msg_LockTokens_Handler.func1({0x277be78, 0xc0027fa000}, {0x20a5920?, 0xc002787200})
	/root/osmosis/x/lockup/types/tx.pb.go:608 +0x78
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x277be78, 0xc0027d7f80}, {0x4c9ae6?, 0x418b4b?}, 0x20fc600?, 0xc001892f48)
	/root/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220728141005-f09814c9e23f/baseapp/msg_service_router.go:113 +0xd2
github.com/osmosis-labs/osmosis/v10/x/lockup/types._Msg_LockTokens_Handler({0x1ef80c0?, 0xc00061b2a8}, {0x277be78, 0xc0027d7f80}, 0x24d1210, 0xc0027ee260)
	/root/osmosis/x/lockup/types/tx.pb.go:610 +0x138
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x277be78, 0xc0027d6300}, {0x278e800, 0xc00273fb80}, {{0xb, 0xa}, {0xc000127f00, 0x9}, 0x5607c6, {0x25a9a48e, ...}, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220728141005-f09814c9e23f/baseapp/msg_service_router.go:117 +0x2f3
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x277be78, 0xc0027d6300}, {0x278e800, 0xc00273fb80}, {{0xb, 0xa}, {0xc000127f00, 0x9}, 0x5607c6, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220728141005-f09814c9e23f/baseapp/baseapp.go:740 +0x5a5
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc0011b2900, 0x3, {0xc0005ca500, 0x12a, 0x12a})
	/root/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220728141005-f09814c9e23f/baseapp/baseapp.go:697 +0xbc5
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).DeliverTx(0xc0011b2900, {{0xc0005ca500?, 0x20?, 0xc0030edb80?}})
	/root/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220728141005-f09814c9e23f/baseapp/abci.go:289 +0x193
github.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync(0xc002c942a0, {{0xc0005ca500?, 0xe8b724?, 0xc002c942a0?}})
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:93 +0x105
github.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync(0xc0042a4420?, {{0xc0005ca500?, 0x20?, 0xb?}})
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:85 +0x26
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x277d1f0?, 0xc002950300}, {0x2785340, 0xc00b90a2e0}, 0xc00021e3c0, {0x278cd20, 0xc001609470}, 0x5607c5?)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/state/execution.go:320 +0x847
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0xa}, {0xc00b91e000, 0x7}}, {0xc00b91e007, 0x9}, 0x1, 0x5607c5, {{0xc00170a0e0, ...}, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0xa}, {0xc00b91e000, 0x7}}, {0xc00b91e007, 0x9}, 0x1, 0x5607c5, {{0xc00170a0e0, ...}, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0xa}, {0xc00b91e000, 0x7}}, {0xc00b91e007, 0x9}, 0x1, 0x5607c5, {{0xc00170a0e0, ...}, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:416 +0x7ae
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc004febb40, {0x278f260, 0xc00199a000})
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3d4
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0xa}, {0xc00b91e000, 0x7}}, {0xc00b91e007, 0x9}, 0x1, 0x5607c5, ...}, ...)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc0011ef180, {0x2778820, 0xc000f8ca00}, 0xc0014e25d0, {0x275e6c0, 0xc00b673788}, 0x1?, 0x0?, 0xc0014e2750, {0x277d1f0, ...}, ...)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x577
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x279b988, 0xc001351500}, {0x0, 0x0}, {0x27824a8, 0xc0011c5110}, ...}, ...)
	/root/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220728141005-f09814c9e23f/server/start.go:262 +0x79b
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00121f680?, {0xc001350900?, 0x0?, 0x3?})
	/root/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220728141005-f09814c9e23f/server/start.go:129 +0x193
```

**Comment by baabeetaa** [comment]
I noticed that if the stack has `updateAccumulation` then there is an unclosed iterator.

Example:
id 69
![Screen_Shot_2022-08-21_at_21_29_43](https://user-images.githubusercontent.com/11970690/185796006-cb868d08-b5b9-4353-8a1a-1b55366dfe65.png)

=> missing close for id 69
![Screen Shot 2022-08-21 at 21 31 15](https://user-images.githubusercontent.com/11970690/185796078-1b893116-db4b-45f3-b536-bec230a8cd98.png)

-----
Another one: id 421
![Screen_Shot_2022-08-21_at_21_32_16](https://user-images.githubusercontent.com/11970690/185796143-ff78b2b6-37fc-4f8e-a164-0b1030d25989.png)

=> missing close for id 421
![Screen Shot 2022-08-21 at 21 33 46](https://user-images.githubusercontent.com/11970690/185796195-bbb436e2-eb22-4d41-9011-b92b9724758b.png)

**Comment by ValarDragon** [comment]
This is awesome! I wonder if we can instrument this iterator close detector in the simulator or main node software somehow. (E.g. check if theres any unclosed iterators at the end of end block or commit)

**Comment by baabeetaa** [comment]
good idea, we can try several options. Maybe i'll make a script or a Dockerfile first to automate the task ( 1. run the container => 2. wait => 3. get result). And we could check it on mainnet/testnet and (devnet?).

**Comment by baabeetaa** [comment]
also, we could add a feature to the tm-db to track open iterators (custom profile or stats) so we can monitor it on running node. It could be helpfull to detect long/heavy queries as well.

**Comment by baabeetaa** [comment]
i've added an instrument to the tmdb on branch `https://github.com/baabeetaa/tm-db/tree/prometheus`

Usage:
- need to replace tmdb to this branch. It supports pebbledb and goleveldb
- enable `prometheus = true` in `config.toml`, it will listen on port 26660 by default
- start the chain (`osmosisd`), the instrument named `db_stats_iterators_unclosed`

```
[root@1f821a4a60a6 osmosis]# curl -s localhost:26660 |grep unclosed
# HELP db_stats_iterators_unclosed number of unclosed iterators
# TYPE db_stats_iterators_unclosed gauge
db_stats_iterators_unclosed 156
```

**Comment by p0mvn** [comment]
Wow amazing work on this
